# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6974f3d26af1f30541b91aea2ba81768dd94321135ff9e7d56f5727198675daf7ab2bd3766f88658f5027566c9048bc498a7f5ccf4faec9cfbb88d2cdf91db18

test:
  secret_key_base: d81c43608d1a7079665dfb53fa6aaf804a76c936ce637d3f7aebf1c97e9aad5c77e929e98aa058d1d3096d94ec093adc2c5d4fc62a50bec842a6eb876e620594

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
